#TODO refactor this
services:
  frontend:
    image: "node:20"
    working_dir: "/var/www/docker"
    volumes:
      - "./src:/var/www/docker"
    ports:
      - "3100:3100" # vite hot reload
    environment:
      - VITE_WS_URL=http://${CONTAINER_SERVICE_PYTHON_IP_ADDRESS}:${WEBSOCKET_PORT}
      - VITE_WS_EVENT=${WEBSOCKET_UPDATE_EVENT}
    command: >
      bash -c "npm install
      && npm run dev"
    networks:
      default:
        ipv4_address: "${CONTAINER_SERVICE_FRONTEND_IP_ADDRESS}"
        aliases:
          - "${CONTAINER_NAME}-nodejs.local"

networks:
  default:
    name: "vpc_${CONTAINER_NAME}"
    driver: "bridge"
    ipam:
      config:
        - subnet: "${CONTAINER_NETWORK_SUBNET}"