services:
  websocket-server:
    image: python:3.11-slim
    working_dir: /app
    command: >
      sh -c "pip install --user -r requirements.txt && python app.py"
    ports:
      - "${DATA_PORT}:8000"
      - "${WEBSOCKET_PORT}:8001"
    volumes:
      - ./websocket:/app:ro
      - pip_packages:/root/.local
    restart: unless-stopped
    networks:
      default:
        ipv4_address: "${CONTAINER_SERVICE_PYTHON_IP_ADDRESS}"
        aliases:
          - "${CONTAINER_NAME}-python.local"

  frontend:
    image: "node:20"
    working_dir: "/var/www/docker"
    volumes:
      - "./frontend:/var/www/docker"
    ports:
      - "3100:3100" # vite hot reload
    environment:
      - VITE_WS_URL=http://${CONTAINER_SERVICE_PYTHON_IP_ADDRESS}:${WEBSOCKET_PORT}
    command: >
      bash -c "npm install
      && npm run dev"
    networks:
      default:
        ipv4_address: "${CONTAINER_SERVICE_FRONTEND_IP_ADDRESS}"
        aliases:
          - "${CONTAINER_NAME}-nodejs.local"

networks:
  default:
    name: "vpc_${CONTAINER_NAME}"
    driver: "bridge"
    ipam:
      config:
        - subnet: "${CONTAINER_NETWORK_SUBNET}"

volumes:
  pip_packages: