# =====================================================
# ===                SDR Hardware                   ===
# =====================================================

# Baseband sample rate used across all workers (Hz)
samp_rate: 2000000          # 2 MHz → ±1 MHz FFT span

# LO frequency for the PlutoSDR (Hz)
lo_freq: 102500000         # 2.45 GHz

# Analog RF bandwidth of the AD936x (Hz)
rf_bandwidth: 2000000        # Should match samp_rate order

# IIO URI of the PlutoSDR
iio_uri: "ip:192.168.2.1"

# PlutoSDR buffer size
buffer_size: 32768


# =====================================================
# ===            Graphics Worker (Waterfall)        ===
# =====================================================

fft_size: 4096
calibration: -20
skip: 30


# =====================================================
# ===             Audio Worker (Demod)              ===
# =====================================================

audio_rate: 48000           # Output audio rate (Hz)
bandwidth: 15000            # Default demod bandwidth (Hz)
freq_offset: 0              # Default (can be overridden)


# =====================================================
# ===              Backend Validation               ===
# =====================================================

# Maximum demodulation bandwidth accepted from frontend (Hz)
MAX_BW_LIMIT: 200000        # 200 kHz

# Max frequency offset = samp_rate/2 is computed internally


# =====================================================
# ===         Global Network / ZMQ / Services       ===
# =====================================================

SDR_HOST: "sdr-server"
SDR_IQ_PORT: 5000
SDR_CONTROL_PORT: 5001

BACKEND_HOST: "backend-controller"

GRAPHICS_UDP_PORT: 9001
AUDIO_UDP_PORT: 9002


# =====================================================
# ===         Backend Worker Pool Configuration     ===
# =====================================================

POOL_SIZE: 3
WORKER_HEADLESS_SERVICE: "audio-workers-headless.default.svc.cluster.local"
WORKER_CONTROL_PORT: 5001


# =====================================================
# ===              WebSocket Events                 ===
# =====================================================

WS_GRAPHICS_EVENT: "graphics_data"
WS_AUDIO_EVENT: "audio_data"
WS_CORRECTION_EVENT: "correction_applied"
WS_URL: "http://localhost"

# =====================================================
# ===              FRONTEND                 ===
# =====================================================
CHANNEL_COUNT: 2
BUFFER_THRESHOLD: 4
MAX_QUEUE_SIZE: 50
RANGE_DB: 80
GAIN_ATTACK: 0.001
GAIN_RELEASE: 0.05

vedant: 10