apiVersion: v1
kind: Service
metadata:
  name: backend-controller
spec:
  type: ClusterIP
  selector:
    app: backend-controller
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: graphics-in
      port: 9001
      targetPort: 9001
      protocol: UDP
    - name: audio-in
      port: 9002
      targetPort: 9002
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-controller
  template:
    metadata:
      labels:
        app: backend-controller
    spec:
      containers:
        - name: backend-controller-container
          image: websdr-transceiver/backend-controller:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: graphics
              containerPort: 9001
            - name: audio
              containerPort: 9002
              protocol: UDP
          volumeMounts:
            - name: sdr-config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: sdr-config-volume
          configMap:
            name: sdr-config
            items:
              - key: config.yaml
                path: config.yaml
